name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: blue-team-agent:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t blue-team-agent:latest .

    - name: Verify environment and run tests
      run: |
        python --version &&
        pip list &&
        python -c 'import tensorflow as tf; print(tf.__version__)' &&
        [ -f /.dockerenv ] && echo 'Running inside Docker' || echo 'Not running inside Docker' &&
        pytest
