name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Python Docker image
      run: docker pull python:3.10

    - name: Build Docker image
      run: docker build -t blue-team-agent:latest .

    - name: Run tests in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app blue-team-agent:latest /bin/sh -c "
          python --version &&
          pip list &&
          python -c 'import tensorflow as tf; print(tf.__version__)' &&
          [ -f /.dockerenv ] && echo 'Running inside Docker' || echo 'Not running inside Docker' &&
          pytest --maxfail=5 --disable-warnings -v > /app/pytest_output.log
        "

    - name: Check for pytest output log
      run: |
        if [ -f ${{ github.workspace }}/pytest_output.log ]; then
          echo "pytest_output.log exists."
        else
          echo "pytest_output.log does not exist."
        fi

    - name: Print test logs
      run: |
        cat ${{ github.workspace }}/pytest_output.log || echo "pytest_output.log not found."
