name: CI

on:
  push:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model
  pull_request:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t blue-team-agent:latest .

    - name: Run tests in Docker container
      run: docker run --rm blue-team-agent:latest pytest
