name: CI

on:
  push:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model
  pull_request:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Change to repository root directory
      run: cd ${{ github.workspace }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed packages
      run: pip list

    - name: Print current working directory
      run: pwd

    - name: Run tests
      run: |
        cd tests
        pytest
