name: CI

on:
  push:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model
  pull_request:
    branches:
      - main
      - clean-history
      - update-cybersecurity-model

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test in Docker container
      run: |
        docker build -t blue-team-agent:latest .
        docker run --rm -v ${{ github.workspace }}:/app -w /app blue-team-agent:latest /bin/bash -c "
          python3 --version &&
          pip list &&
          pwd &&
          ls -la &&
          pytest
        "
